spring:
  application:
    name: thinkmall-gateway

server:
  port: 5555

# zuul路由配置
zuul:
  retryable: true
  add-host-header: true
  routes:
    user:
      path: /thinkmall-sso-web/**
      serviceId: thinkmall-sso-web

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'