spring:
  application:
    name: thinkmall-trubine

server:
  port: 3001

turbine:
  app-config: THINKMALL-SSO-WEB
  combine-host-port: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:7001/eureka